name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Check types
        run: |
          python -m mypy --follow-imports=normal medcat2
      - name: Ruff linting
        run: |
          ruff check medcat2
      - name: Flake8 lint
        run: |
          flake8 medcat2
      - name: Test
        run: |
          timeout 10m python -m unittest discover
